name: autopost

on:
  schedule:
    - cron: "25 4 * * *"
    - cron: "18 10 * * *"
    - cron: "51 17 * * *"
    - cron: "47 23 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Create env file
        run: echo '${{ secrets.ENV_FILE }}' > .env

      - name: Installing dependencies
        run: pip install -r --no-cache-dir requirements.txt

      - name: Run the project
        run: python rainvid/main.py
